### PR TITLE
1-1. Beginning with Python.ipynbの翻訳

### PR DESCRIPTION
**Pull request by okusama27**
1-1. Beginning with Python.ipynbを翻訳したよ

以下のファイルをレビューしてください。
notebooks-WORK/1-1. kame-chan-Beginning with Python.ipynb

### CODE REVIEW

**Comment by okusama27** [comment]
Very Sorry. I mistook my PR's place. I close it.

**Comment by Cheukting** [comment]
@okusama27 don't feel sorry, I see that you are translating it into Japanese. Is it for the event in October? (PyCon APAC) I am planning to do a Japanese translation as well. Maybe it is a good idea to put the Japanese translation into a `Japanese` branch in this repo so the community can use.

**Comment by Cheukting** [comment]
@okusama27 when you are ready you can also make a PR to add the event on our website via here: https://github.com/HumbleData/HumbleData.github.io/tree/master/_posts

**Comment by okusama27** [comment]
@Cheukting Yes, it's for the event PyCon APAC in October. Now, we are holding a trancelating event with PyLadies Tokyo members.
Our organiser said "If we finish the trancelation, I create new PR". That time, she will ask you how to do.

**Comment by okusama27** [comment]
@Cheukting  Thank you for letting me know it. I share the information to our members.

**Pull request closed without merging**
